services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0 --port 8545
    ports:
      - "8545:8545"

  contracts-deployer:
    image: ghcr.io/foundry-rs/foundry:latest
    depends_on:
      - anvil
    working_dir: /contracts
    volumes:
      - ./contracts:/contracts
    command: >
      forge create src/Escrow.sol:Escrow --rpc-url http://anvil:8545 --private-key ${DEPLOYER_PRIVATE_KEY} --broadcast --constructor-args ${OWNER_ADDRESS}
    environment:
      - DEPLOYER_PRIVATE_KEY=${DEPLOYER_PRIVATE_KEY}
      - OWNER_ADDRESS=${OWNER_ADDRESS}
  copy-artifacts:
    image: alpine
    depends_on:
      - contracts-deployer
    volumes:
      - ./frontend/src/contracts:/contracts_dst
      - ./out:/contracts_src
    command: >
      sh -c "rm -rf /contracts_dst/* &&
             cp /contracts_src/Escrow.sol/Escrow.json /contracts_dst/"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    working_dir: /backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm start

  frontend:
    build: ./frontend
    depends_on:
      - backend
      - copy-artifacts
    ports:
      - "5173:80"

volumes:
  db_data:
